version: 0.0

os: linux

files:
  - source: /
    destination: /home/ubuntu/docker-project
    overwrite: true

hooks:

  AfterInstall:
    - location: deploy/after-install.sh
      timeout: 300
      runas: root